class StudentCALocators:
    COMPLETION_POPUP_CLOSE_BUTTON = "//button[@class='cm-close-btn']"
    MATCHED_ROLE = "//div[text()='Matched Roles']"
    PASSIONS_HEADER = "//h4[text()='Passions']"
    REVIEW_BUTTON = "//button[text()='Review']"
    ART_AND_DESIGN_HEADER = "//span[text()='Arts & Design']"
    DRAWING_AND_ILLUSTRATION_INPUT = "//span[text()='Drawing & Illustration']"
    FASHION_DESIGN_INPUT = "//span[text()='Fashion Design']"
    CLOSE_PASSION_BUTTON = "//button[text()='✕']"
    BUSINESS_AND_MARKETING_HEADER = "//span[text()='Business & Marketing']"
    E_COMMERCE_OPTION = "//span[text()='E‑commerce']"
    SUBMIT_BUTTON = "//button[text()='Submit']"
    PROFILE_HEADER = "//h4[normalize-space()='Profile']"
    INTERESTS_CARD = "(//img[@class='wf_image qmc-icon no-js-svg%3e'])[1]"
    APTITUDES_CARD = "(//div[@class='questionnaire-mini-card qmc-completed'])[2]"
    VALUES_CARD = "(//div[@class='questionnaire-mini-card qmc-completed'])[3]"
    REATTEMPT_BUTTONS = "//button[text()='Reattempt']"
    INTERESTS_REATTEMPT_BUTTON = "(//button[text()='Reattempt'])[1]"
    APTITUDES_REATTEMPT_BUTTON = "(//button[text()='Reattempt'])[2]"
    VALUES_REATTEMPT_BUTTON = "(//button[text()='Reattempt'])[3]"
    QUESTIONNAIRES_CHOOSE_BUTTON = "(//button[text()='Choose'])[1]"
    QUESTIONNAIRE_IFRAME = "iframe.qv2-iframe"
    CHOOSE_ONE_CARD = "(//div[@class='scenario-card'])[1]"
    FUN_EMOJI_CARD = "(//div[@class='fun-meter-card-h'])[2]"
    TWO_CARDS_PRESENT = "(//div[@class='forced-card selected'])[1]"
    SCENARIO_CARDS = "//div[contains(@class,'scenario-card')]"
    FUN_EMOJI_CARDS = "//div[contains(@class,'fun-meter-card-h')]"
    FORCED_CARDS = "//div[contains(@class,'forced-card')]"
    ILLUSTRATED_SCENARIO_CARDS = "(//div[@class='illustrated-scenario-card'])[1]"
    ANY_QUESTION_CARD = (
        "//div[contains(@class,'scenario-card') or "
        "contains(@class,'fun-meter-card-h') or "
        "contains(@class,'forced-card')]"
    )
    START_APTITUDES = "(//button[text()='Choose'])[1]"
    START_VALUES = "(//button[text()='Choose'])[1]"
    SLIDER_CHOOSE_BUTTON = "(//button[text()='Choose'])[2]"
    RETAKE_BUTTON = "//button[text()='Retake']"
    CHOOSING_SLIDER = "//div[@class='ant-slider ant-slider-horizontal']"
    QUESTION_SLIDER = "//div[@role='slider']"
    CHOOSE_SLIDER_OPTION_9 = "//div[@role='slider']"
    NEXT_BUTTON = "//button[text()='Next']"
    BACK_ARROW = "//img[@class='wf_image back-arrow no-js-svg%3e']"
    GO_TO_MATCHED_ROLES_BUTTON = "//span[text()='Go to Matched Roles']"
    WITHOUT_COLLEGE_DEGREE = "//span[text()='Without College Degree']"
    VALIDATE_RECOMMENDED_ROLES_PASSION_HEADER_MATCHED_COUNT = "(//span[@class='header-count'])[1]"
    VALIDATE_RECOMMENDED_ROLES_QUESTIONNAIRES_HEADER_MATCHED_COUNT = "(//span[@class='header-count'])[2]"
    SEARCH_ROLES_HEADER = "//div[text()='Search Roles']"
    SEARCH_ROLES_INPUT = "//input[@placeholder='Search for a Job Role']"
    VALIDATE_RESULTS_HEADER = "//h4[text()='Results']/following::h4[1]"
    ADD_SAVE = "(//h4[text()='Save'])[1]"
    FIRST_RESULT_SAVED_STATE = "(//h4[text()='Saved'])[1]"
    SAVED_MENU_HEADER = "//div[text()='Saved']"
    COMPARE_ROLES = "//button[@class='compare-sticky-strip__btn']"
    FIRST_FAV_CHECKBOX = "(//div[@class='fav-checkbox'])[1]"
    SECOND_FAV_CHECKBOX = "(//div[@class='fav-checkbox'])[2]"
    COMPARE_BUTTON = "//button[contains(text(),'Compare')]"
    SHARE_REPORT_HEADER = "//div[text()='Share Report']"
    SHARE_REPORT_BUTTON = "//span[text()='Share']"
    SELF_REVIEW_TAB = "//div[text()='Self Review']"
    MATCHED_ROLES_TAB = "(//div[text()='Matched Roles'])[2]"
    SAVED_ROLES_TAB = "//div[@class='menu-container  selected']"
    REMOVE_SAVED_JOB = "//h4[text()='Saved']"
    HELP_ICON = "//button[text()='Help?']"
    ABOUT_HEADER = "//h1[text()='About']"
    PROFILE_ICON = "//div[contains(@class,'profile_container')]"
    PROFILE_MENU_ITEM = (
        "//div[contains(@class,'ant-dropdown') and "
        "not(contains(@class,'ant-dropdown-hidden'))]//h1"
    )
    ABOUT_MENU_ITEM = (
        "//div[contains(@class,'ant-dropdown') and "
        "not(contains(@class,'ant-dropdown-hidden'))]//h1[text()='About']"
    )
    WITH_COLLEGE_DEGREE = "//span[normalize-space(text())='With College Degree']"
    RECOMMENDED_ROLES_HEADER = "//h4[normalize-space(text())='Recommended Roles']"
    WHY_THIS_RECOMMENDATION = "//h4[normalize-space(text())='Why this recommendation?']"
    NO_RELATED_JOBS = "//*[normalize-space(text())='No Related Jobs']"
    SAVED_ROLES_HEADER = "//*[contains(text(),'Saved Roles')]"
    COMPARE_ROLES_LINK = "//div[normalize-space(text())='Compare roles']"
    ABOUT_APP_TITLE = "//h3[normalize-space(text())='My Career Advisor']"
    ABOUT_KEY_FEATURES = "//h4[normalize-space(text())='Key Features:']"
    ROLE_CARD = "//div[contains(@class,'role-container')]"