class MyCareerAdvisorLocators:
    GOT_IT_POPUP_BUTTON = "//span[text()='Got It']"
    HOME = "//div[text()='Home']"
    MY_CAREER_ADVISOR = "//h6[text()='My Career Advisor']"
    PASSIONS_HEADER = "//h4[text()='Passions']"
    PASSION_REVIEW_BUTTON = "//button[text()='Review']"
    ARTS_AND_DESIGN = "//*[contains(text(),'Arts & Design')]"
    DRAWING_AND_ILLUSTRATION_CHECKBOX = "//input[@id='drawingAndIllustration']"
    # The visible checkbox button is the <label>; clicking the hidden <input>
    # doesn't fire the selection that enables Submit.
    DRAWING_AND_ILLUSTRATION_LABEL = "//label[@for='drawingAndIllustration']"
    SUBMIT_BUTTON = "//button[text()='Submit']"
    QUESTIONNAIRES_HEADER = "//h4[text()='Questionnaires']"
    APTITUDE_REVIEW_BUTTON = "(//button[text()='Review'])[1]"
    REATTEMPT_BUTTON = "//button[text()='Reattempt']"
    SLIDER_CHOOSE_BUTTON = "(//button[text()='Choose'])[2]"
    SLIDER_HANDLE = "//div[@class='questionnaire-slider-container'][1]//div[contains(@class,'ant-slider-handle')]"
    UPDATE_BUTTON = "//button[text()='Update']"
    GO_TO_MATCHED_ROLES_BUTTON = "//button[text()='Go to Matched Roles']"
    WITHOUT_COLLEGE_DEGREE = ("//span[normalize-space()='Without College Degree'"
                              " or contains(normalize-space(), 'WITHOUT_COLLEGE_DEGREE')]")
    VALIDATE_HEADER_COUNT = "//span[@class='header-count']"
    SEARCH_ROLES_HEADER = "//h4[text()='Search Roles']"
    SEARCH_FOR_JOB_ROLE_INPUT = "//input[@placeholder='Search for a Job Role']"
    RESULTS_HEADER = "//h4[text()='Results']/following::h4[1]"
    ADD_FAVOURITE = "//h4[text()='Favourite']"
    FAVOURITES_HEADER = "//h4[text()='Favourites']"
    SHARE_REPORT = "(//h4[text()='Share Report'])[1]"
    SHARE_BUTTON = "//button[text()='Share']"
    REMOVE_FAVOURITE = "//h4[text()='Favourite']"
    ROLES_SAVED = "//*[contains(text(), 'Role') and contains(text(), 'Saved')]"
    VALIDATE_FAVOURITE_ROLES_HEADER = "//h4[contains(text(), 'Favourite Roles')]"
    